name: PureChat
main: _64FF00\PureChat\PureChat
version: "1.2.3"
api: [1.8.0]
load: STARTUP
author: 64FF00
website: https://github.com/PurePlugins/PureChat
depend: [PurePerms]
softdepend: [FactionsPro]
